apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  labels:
    app: safe-config-service
  name: safe-config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: safe-config-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: safe-config-service
    spec:
      containers:
        - image: sovryn/safe-config
          imagePullPolicy: Always
          envFrom:
          - secretRef:
              name: safe-config-service
          - secretRef:
              name: safe-config-service-secret
          name: web
          resources: {}
          tty: true
          volumeMounts:
            - mountPath: /nginx
              name: nginx-shared
        - image: nginx:1.20-alpine
          name: nginx
          envFrom:
          - secretRef:
              name: safe-config-service
          - secretRef:
              name: safe-config-service-secret
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - name: nginxconf
              mountPath: /etc/nginx/templates
            - mountPath: /nginx
              name: nginx-shared
      restartPolicy: Always
      volumes:
        - name: nginx-shared
          emptyDir: {}
        - name: nginxconf
          secret:
            secretName: safe-config-service-nginx
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: safe-config-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:768438872063:certificate/9fa02b26-0ee5-4301-bdd6-8474344885ff
spec:
  selector:
    app: safe-config-service
  ports:
    - port: 443
      targetPort: 80
  type: LoadBalancer
---
